### ISSUE TITLE
Eliminate the need for suffix input

### ISSUE THREAD

**Issue by joebochill** [pxblue/automation#28]
#### Describe the desired behavior
The suffix is redundant and error prone (forgetting the dash). The suffix is (should) always be the package name minus '@pxblue/'. We should be able to infer the tag from the package.json file instead of taking it as an input.

#### Describe the current behavior
PACKAGE is read from the package.json but TAG_SUFFIX is passed via user input.

#### Is this request related to a current issue?
Just noticed that I think i forgot the '-' in the SUFFIX for the repos that I set up. This would simplify the process and eliminate those kinds of mistakes.

#### Additional Context

We could keep the suffix functionality in the case that we want to add an _additional_ sufficx, but the we should be able to get the main tag contents all from package.json.

**Comment by daileytj** [comment]
This has been fixed in a recent PR #29
